# Generated by Django 5.1.5 on 2025-01-30 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('zip_code', models.CharField(blank=True, default='', max_length=5, unique=True)),
                ('temp_min', models.FloatField(null=True)),
                ('temp_max', models.FloatField(null=True)),
                ('icon', models.CharField(blank=True, default='', max_length=256)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
