# Generated by Django 5.1.5 on 2025-01-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Name of this location.', max_length=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
