# Generated by Django 5.1.5 on 2025-01-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(default='20810', max_length=5),
        ),
    ]
