# Generated by Django 5.1.5 on 2025-01-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_city_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
