# Generated by Django 5.1.5 on 2025-01-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_city_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
