# Generated by Django 5.1.5 on 2025-01-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_city_state_alter_city_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(default='00000', max_length=5, unique=True),
        ),
    ]
