# Generated by Django 5.1.5 on 2025-01-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_city_state_alter_city_zip_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Location',
        ),
    ]
